apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- literals:
  - database-name=quarkus
  - database-password=quarkus
  - database-user=quarkus
  name: postgres-secret
  type: Opaque
resources:
- postgres-dc.yml
- postgres-svc.yml
