apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  creationTimestamp: "2020-02-10T15:11:40Z"
  labels:
    template: postgresql-ephemeral-template
    template.openshift.io/template-instance-owner: a3f69016-4c17-11ea-98c2-02e75b0fdc8b
  name: postgresql
  namespace: kustomize
  resourceVersion: "12902"
  selfLink: /api/v1/namespaces/kustomize/services/postgresql
  uid: a3fa1e08-4c17-11ea-98c2-02e75b0fdc8b
spec:
  clusterIP: 172.30.24.181
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
