# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'
- task: Docker@2
  inputs:
    containerRegistry: 'quarkus-nexus'
    repository: 'quarkus-hello-world'
    command: 'buildAndPush'
    Dockerfile: '**/src/main/docker/Dockerfile.multistage'
    buildContext: '**/.'
        
# - task: oc-setup@2
#   inputs:
#     openshiftService: 'azure-devops-quarkus'
# - task: oc-cmd@2
#   inputs:
#     openshiftService: 'azure-devops-quarkus'
#     cmd: '-n quarkus new-build --strategy=docker --binary --name quarkus-hello-world'
# - task: oc-cmd@2
#   inputs:
#     openshiftService: 'azure-devops-quarkus'
#     cmd: '-n quarkus start-build --from-dir="."  bc/quarkus-hello-world'