# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: oc-setup@2
  inputs:
    openshiftService: 'azure-devops-pru-test'
- task: oc-cmd@2
  inputs:
    openshiftService: 'azure-devops-pru-test'
    cmd: '-n pru-test new-build --strategy=docker --binary --name quarkus-hello-world'
- task: oc-cmd@2
  inputs:
    openshiftService: 'azure-devops-pru-test'
    cmd: '-n pru-test start-build --from-dir="."  bc/quarkus-hello-world'
