{{- if not .Values.localPostgres.disabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "quarkus-hello-world.fullname" . }}-postgresql
  labels:
    {{- include "quarkus-hello-world.labels" . | nindent 4 }}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "quarkus-hello-world.localPostgresSelectorLabels" . | nindent 4 }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "quarkus-hello-world.localPostgresSelectorLabels" . | nindent 4 }}
    spec:
      containers:
        - name: container
          image: {{ .Values.localPostgres.image }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              value: quarkus
            - name: POSTGRESQL_PASSWORD
              value: quarkus
            - name: POSTGRESQL_DB
              value: quarkus
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "quarkus-hello-world.fullname" . }}-postgresql
  labels:
    {{- include "quarkus-hello-world.labels" . | nindent 4 }}
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: tcp-postgresql
      protocol: TCP
      port: 5432
      targetPort: tcp-postgresql
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    {{- include "quarkus-hello-world.localPostgresSelectorLabels" . | nindent 4 }}
{{- end }}