apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-hello-world-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: local-maven-repo

  params:
    - name: SOURCE_URL
      default: https://github.com/mikecroft/quarkus-hello-world.git
    
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.SOURCE_URL)
        - name: deleteExisting
          value: "true"

    - name: maven-build
      taskRef:
        name: maven-graalvm
      params:
        - name: GOALS
          value:
            - package
            # - -Pnative
      runAfter:
        - fetch-repo
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: local-maven-repo

    - name: build-container-image
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/qks/quarkus-hello-world
        - name: DOCKERFILE
          value: src/main/docker/jvm.Dockerfile
        - name: EXTRA_ARGS
          value: '--skip-tls-verify' # self-signed certs
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - maven-build