apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-hello-world-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: local-maven-repo
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/mikecroft/quarkus-hello-world.git
        - name: deleteExisting
          value: "true"      
    - name: maven-build
      taskRef:
        name: maven
      params:
        - name: GOALS
          value:
            - package
            - -Pnative
      runAfter:
        - fetch-repo
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: local-maven-repo
    - name: build-container-image
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/qks/quarkus-hello-world
        - name: DOCKERFILE
          value: src/main/docker/native.Dockerfile
      runAfter:
        - maven-build
      workspaces:
        - name: source
          workspace: shared-workspace