apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: quarkus-hello-world-pipeline-run
spec:
  pipelineRef:
    name: quarkus-hello-world-pipeline
  serviceAccountName: default

  params:
    - name: SOURCE_URL
      value: https://github.com/mikecroft/quarkus-hello-world.git
    - name: PROJECT
      value: a-tekton-test
    - name: APP_NAME
      value: quarkus-hello-world

  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: git-source-pvc
    - name: local-maven-repo
      persistentVolumeClaim:
        claimName: mvn-repo-pvc