apiVersion: v2
name: quarkus-hello-world
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: latest

dependencies:
- name: postgresql
  version: ~15.0.0
  repository: "https://charts.bitnami.com/bitnami"
  condition: localPostgres.disabled
