---
# Source: quarkus-hello-world/templates/build/pipeline.yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: release-name-quarkus-hello-world
spec:
  tasks:
    - name: git-clone
      params:
      - name: url
        value: https://github.com/mikecroft/quarkus-hello-world.git
      - name: revision
        value: master
      - name: submodules
        value: "true"
      - name: depth
        value: "1"
      - name: sslVerify
        value: "true"
      - name: crtFileName
        value: ca-bundle.crt
      - name: deleteExisting
        value: "true"
      - name: verbose
        value: "true"
      - name: gitInitImage
        value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:66f219b4d54a41b945cb5715ecd1fbb5d25431cf8dad4b06914a4cdc65b298cc
      - name: userHome
        value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: build
    - name: maven
      params:
      - name: MAVEN_IMAGE
        value: registry.redhat.io/ubi8/openjdk-17@sha256:a8165bc2cd5051a96d6937e25ed03155bbd4b731da6e58cebfe2ea83209c16d8
      - name: GOALS
        value:
        - package
        - -DskipTests
      - name: PROXY_PROTOCOL
        value: http
      - name: CONTEXT_DIR
        value: .
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: build
        - name: maven-settings
          workspace: build
    - name: buildah
      params:
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{
          include "quarkus-hello-world.fullname" . }}
      - name: BUILDER_IMAGE
        value: registry.redhat.io/rhel8/buildah@sha256:b48f410efa0ff8ab0db6ead420a5d8d866d64af846fece5efb185230d7ecf591
      - name: STORAGE_DRIVER
        value: vfs
      - name: DOCKERFILE
        value: ./Dockerfile
      - name: CONTEXT
        value: .
      - name: TLSVERIFY
        value: "true"
      - name: FORMAT
        value: oci
      - name: SKIP_PUSH
        value: "false"
      runAfter:
        - maven
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: build
  workspaces:
    - name: build
