{{- if .Values.route.enabled -}}
{{- $fullName := include "quarkus-hello-world.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  creationTimestamp: "2020-02-04T16:07:02Z"
  labels:
    {{- include "quarkus-hello-world.labels" . | nindent 4 }}
  name: {{ $fullName }}
spec:
  host: ""
  port:
    targetPort: {{ $svcPort }}-tcp
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  wildcardPolicy: None
# See: https://github.com/openshift/origin/issues/24060
#      https://bugzilla.redhat.com/show_bug.cgi?id=1773682
status:
  ingress:
  - host: ""
{{- end }}